### ISSUE TITLE
Bug?: Clicking cancel on open model shouldn't give me an error

### ISSUE THREAD

**Issue by ashifolfi** [craftablescience/ChiraEngine#16]
### Describe the Bug

Clicking cancel on the open model dialog will result in you being given an error about no resource given

This is a bit weird and shouldn't be a thing tbh

cancel means I want to cancel the action. It shouldn't complain that I didn't give it anything.

### To Reproduce

1. Hit open model
2. hit cancel

### Operating System

Mac (Unsure if this happens elsewhere. haven't tested)

**Comment by craftablescience** [comment]
The error message pops up when you pass an invalid model path, but since filters exist and paths should always be valid I can remove it
