### ISSUE TITLE
Add automatic code formatting tool

### ISSUE THREAD

**Issue by craftablescience** [craftablescience/ChiraEngine#48]
### Component to Improve

Other

### Describe Your Suggestion

We should have a code formatter to preserve and enforce the current code style. I'm thinking `clang-format`

- [ ] Should work in an IDE
- [ ] Should block uncompliant PRs

**Comment by ashifolfi** [comment]
that might be a bit difficult for me to maintain unless the formatting tool supports KDevelop which is what I'm currently using for IDE choice (VSCode's support for anything is shit and the C++ extension constantly breaks resulting in BS errors that don't exist)

**Comment by ashifolfi** [comment]
The soon-to-be existence of a `.editorconfig` file should help somewhat with this. Directing editors like Visual Studio and Visual Studio Code which support the VSC++ EditorConfig properties to use the current formatting style (with a few improvements) present throughout ChiraEngine.

**Comment by craftablescience** [comment]
The editorconfig file should be sufficient for this honestly, autoformatters usually suck
