### ISSUE TITLE
[repo workflow] Use Ninja in place of Makefiles

### ISSUE THREAD

**Issue by ashifolfi** [craftablescience/ChiraEngine#53]
### Component to Improve

Other

### Describe Your Suggestion

Through various testing on multiple projects including ChiraEngine I've found that Ninja can be significantly faster than makefiles in compiles. It might be beneficial to swap the remaining Unix Makefiles workflows over to Ninja

**Comment by craftablescience** [comment]
Done Linux side, only need to do this for the macOS jobs now
